chore: try default solx amd64 runner instead of self-hosted

diff --git a/.github/workflows/forge-benchmarks.yaml b/.github/workflows/forge-benchmarks.yaml
--- a/.github/workflows/forge-benchmarks.yaml
+++ b/.github/workflows/forge-benchmarks.yaml
@@ -68,7 +68,7 @@ env:
 jobs:
 
   build-solx:
-    runs-on: self-hosted
+    runs-on: solx-linux-amd64
     container:
       image: ghcr.io/matter-labs/zksync-llvm-runner:latest
     strategy:
@@ -77,11 +77,11 @@ jobs:
         type: ["reference", "candidate"]
     steps:
 
-      - name: Tmp cleanup
-        run: |
-          rm -rf /__w/solx || true
-          sudo rm -rf /__w/solx || true
-          mkdir -p /__w/solx/solx
+      # - name: Tmp cleanup
+      #   run: |
+      #     rm -rf /__w/solx || true
+      #     sudo rm -rf /__w/solx || true
+      #     mkdir -p /__w/solx/solx
 
       - name: Checkout source
         uses: actions/checkout@v5
@@ -174,7 +174,7 @@ jobs:
 
   test:
     needs: [build-solx, prepare-projects]
-    runs-on: self-hosted
+    runs-on: solx-linux-amd64
     env:
       DEFAULT_ITERATIONS: 1
       FOUNDRY_INVARIANT_RUNS: 0
@@ -194,11 +194,11 @@ jobs:
         project: ${{ fromJSON(needs.prepare-projects.outputs.projects) }}
     steps:
 
-      - name: Tmp cleanup
-        run: |
-          rm -rf /__w/solx || true
-          sudo rm -rf /__w/solx || true
-          mkdir -p /__w/solx/solx
+      # - name: Tmp cleanup
+      #   run: |
+      #     rm -rf /__w/solx || true
+      #     sudo rm -rf /__w/solx || true
+      #     mkdir -p /__w/solx/solx
 
       - name: Checkout
         uses: actions/checkout@v5
@@ -488,7 +488,7 @@ jobs:
 
   # prepare-md-tables:
   #   if: ${{ inputs.print-markdown-tables == 'true' }}
-  #   runs-on: self-hosted
+  #   runs-on: solx-linux-amd64
   #   needs: test
   #   steps:
 
diff --git a/.github/workflows/hardhat-tests.yaml b/.github/workflows/hardhat-tests.yaml
--- a/.github/workflows/hardhat-tests.yaml
+++ b/.github/workflows/hardhat-tests.yaml
@@ -29,16 +29,16 @@ jobs:
 
   build-solx:
     if: ${{ inputs.solx-version == '' }}
-    runs-on: self-hosted
+    runs-on: solx-linux-amd64
     container:
       image: ghcr.io/matter-labs/zksync-llvm-runner:latest
     steps:
 
-      - name: Tmp cleanup
-        run: |
-          rm -rf /__w/solx || true
-          sudo rm -rf /__w/solx || true
-          mkdir -p /__w/solx/solx
+      # - name: Tmp cleanup
+      #   run: |
+      #     rm -rf /__w/solx || true
+      #     sudo rm -rf /__w/solx || true
+      #     mkdir -p /__w/solx/solx
 
       - name: Checkout source
         uses: actions/checkout@v5
@@ -114,7 +114,7 @@ jobs:
     if: |
       always() &&
       (needs.build-solx.result == 'skipped' || needs.build-solx.result == 'success')
-    runs-on: self-hosted
+    runs-on: solx-linux-amd64
     env:
       DEFAULT_ITERATIONS: 20
     outputs:
@@ -128,11 +128,11 @@ jobs:
         project: ${{ fromJSON(needs.prepare-projects.outputs.projects) }}
     steps:
 
-      - name: Tmp cleanup
-        run: |
-          rm -rf /__w/solx || true
-          sudo rm -rf /__w/solx || true
-          mkdir -p /__w/solx/solx
+      # - name: Tmp cleanup
+      #   run: |
+      #     rm -rf /__w/solx || true
+      #     sudo rm -rf /__w/solx || true
+      #     mkdir -p /__w/solx/solx
 
       - name: Checkout
         uses: actions/checkout@v5
diff --git a/.github/workflows/integration-tests.yaml b/.github/workflows/integration-tests.yaml
--- a/.github/workflows/integration-tests.yaml
+++ b/.github/workflows/integration-tests.yaml
@@ -18,7 +18,7 @@ permissions:
 jobs:
 
   tests:
-    runs-on: self-hosted
+    runs-on: solx-linux-amd64
     container:
       image: ghcr.io/matter-labs/zksync-llvm-runner:latest
       options: -m 110g
@@ -27,11 +27,11 @@ jobs:
       SOLC_PREFIX: ${{ github.workspace }}/era-solidity/build
     steps:
 
-      - name: Tmp cleanup
-        run: |
-          rm -rf /__w/solx || true
-          sudo rm -rf /__w/solx || true
-          mkdir -p /__w/solx/solx
+      # - name: Tmp cleanup
+      #   run: |
+      #     rm -rf /__w/solx || true
+      #     sudo rm -rf /__w/solx || true
+      #     mkdir -p /__w/solx/solx
 
       - name: Checkout
         uses: actions/checkout@v5
@@ -72,7 +72,7 @@ jobs:
 
 
   benchmarks:
-    runs-on: self-hosted
+    runs-on: solx-linux-amd64
     container:
       image: ghcr.io/matter-labs/zksync-llvm-runner:latest
     strategy:
@@ -84,11 +84,11 @@ jobs:
       SOLC_PREFIX: ${{ github.workspace }}/era-solidity/build
     steps:
 
-      - name: Tmp cleanup
-        run: |
-          rm -rf /__w/solx || true
-          sudo rm -rf /__w/solx || true
-          mkdir -p /__w/solx/solx
+      # - name: Tmp cleanup
+      #   run: |
+      #     rm -rf /__w/solx || true
+      #     sudo rm -rf /__w/solx || true
+      #     mkdir -p /__w/solx/solx
 
       - name: Checkout
         uses: actions/checkout@v5
