chore: add results analysis

diff --git a/.github/workflows/hardhat-tests.yaml b/.github/workflows/hardhat-tests.yaml
--- a/.github/workflows/hardhat-tests.yaml
+++ b/.github/workflows/hardhat-tests.yaml
@@ -215,13 +215,13 @@ jobs:
                 git clone --depth 1 "${REPO}" "${GITHUB_WORKSPACE}/projects/${PROJECT}" --recurse-submodules
                 cd "${GITHUB_WORKSPACE}/projects/${PROJECT}"
                 echo "Running tests for ${PROJECT} with ${COMPILER} via-ir=${VIA_IR}"
-          
+
                 # Install dependencies
                 ${BUILD_BIN} install
-          
+
                 # Clean project
                 ${BUILD_BIN} run clean
-          
+
                 # Build project
                 [ ${COMPILER} == 'solx' ] && USE_SOLX="true" || USE_SOLX="false"
                 [ ${VIA_IR} == 'true' ] && VIA_IR_SUFFIX="-via-ir" || VIA_IR_SUFFIX=""
@@ -280,209 +280,103 @@ jobs:
           name: results-${{ strategy.job-index }}
           path: 'sol*/'
 
-#  prepare-compatibility-table:
-#    runs-on: ubuntu-latest
-#    needs: test
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v4
-#
-#      - name: Download reports
-#        uses: actions/download-artifact@v4
-#        with:
-#          path: data
-#          merge-multiple: 'true'
-#
-#      - name: Prepare compatibility table
-#        run: |
-#          echo "| Project     | Mode     | Compiled / Total       | Passed / Total         |" > report.md
-#          echo "|-------------|----------|------------------------|------------------------|" >> report.md
-#
-#          PROJECTS=$(yq '. as $root | keys[]' .github/hardhat-projects.toml | tr '\n' ' ')
-#          for PROJECT in ${PROJECTS}; do
-#            for MODE in "default" "viaIR"; do
-#              if [ "${MODE}" = "default" ]; then
-#                JSON="data/solx/build_${PROJECT}.json"
-#                RUN_JSON="data/solx/test_${PROJECT}.json"
-#                RUN_REF_JSON="data/solc/test_${PROJECT}.json"
-#              else
-#                JSON="data/solx-via-ir/build_${PROJECT}.json"
-#                RUN_JSON="data/solx-via-ir/test_${PROJECT}.json"
-#                RUN_REF_JSON="data/solc-via-ir/test_${PROJECT}.json"
-#              fi
-#
-#              TEST_TOTAL=0
-#              TEST_PASSED=0
-#              if jq empty "${RUN_JSON}" > /dev/null 2>&1 && [ -s "${RUN_JSON}" ]; then
-#                TEST_RESULTS_JSON=$(
-#                jq '
-#                  reduce to_entries[] as $contract (
-#                    {total: 0, success: 0};
-#                    reduce ($contract.value.test_results | to_entries)[] as $test (
-#                      .;
-#                      .total += 1 |
-#                      .success += (if $test.value.status == "Success" then 1 else 0 end)
-#                    )
-#                  )' "${RUN_JSON}"
-#                )
-#                REF_TEST_RESULTS_JSON=$(
-#                jq '
-#                  reduce to_entries[] as $contract (
-#                    {total: 0, success: 0};
-#                    reduce ($contract.value.test_results | to_entries)[] as $test (
-#                      .;
-#                      .total += 1 |
-#                      .success += (if $test.value.status == "Success" then 1 else 0 end)
-#                    )
-#                  )' "${RUN_REF_JSON}"
-#                )
-#                # Take number of successful tests from solc as total
-#                TEST_TOTAL=$(echo "${REF_TEST_RESULTS_JSON}" | jq -r '.success')
-#                TEST_PASSED=$(echo "${TEST_RESULTS_JSON}" | jq -r '.success')
-#              fi
-#
-#              if [ ! -s "$JSON" ]; then
-#                echo "No data for ${PROJECT} [$MODE]"
-#                continue
-#              fi
-#
-#              TOTAL=0
-#              PASSED=0
-#              if jq empty "${JSON}" > /dev/null 2>&1 && [ -s "${JSON}" ]; then
-#                if [[ "${RUN_TIME}" == null ]]; then RUN_TIME=0; fi
-#                TOTAL=$(jq -r '.build_infos[0].source_id_to_path | length' "$JSON")
-#                FAILURES=$(jq -r '[.errors[] | select(.type == "Error")] | length' "$JSON")
-#                PASSED=$((TOTAL - FAILURES))
-#              fi
-#
-#              # Generate compile bar
-#              COMPILE_BAR=""
-#              COMPILE_PERCENT=0
-#              if [[ "$TOTAL" -gt 0 ]]; then
-#                COMPILE_PERCENT=$((PASSED * 100 / TOTAL))
-#              fi
-#              FILLED=$(( COMPILE_PERCENT / 10 ))
-#              for i in $(seq 1 10); do
-#                [ "$i" -le "$FILLED" ] && COMPILE_BAR+="🟩" || COMPILE_BAR+="⬜"
-#              done
-#
-#              # Generate test bar
-#              TEST_BAR=""
-#              TEST_PERCENT=0
-#              if [[ "$TEST_TOTAL" -gt 0 ]]; then
-#                TEST_PERCENT=$((TEST_PASSED * 100 / TEST_TOTAL))
-#              fi
-#              FILLED=$(( TEST_PERCENT / 10 ))
-#              for i in $(seq 1 10); do
-#                [ "$i" -le "$FILLED" ] && TEST_BAR+="🟩" || TEST_BAR+="⬜"
-#              done
-#              if [[ "$TEST_TOTAL" -eq 0 ]]; then
-#                TEST_BAR="🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩"
-#              fi
-#              TEST_COLUMN=$(printf "%-10s %4d / %4d" "${TEST_BAR}" "${TEST_PASSED}" "${TEST_TOTAL}")
-#
-#              if [ "$MODE" = "default" ]; then
-#                printf "| %-11s | %-8s | %-10s %4d / %4d | %s |\n" \
-#                  "${PROJECT}" "${MODE}" "${COMPILE_BAR}" "${PASSED}" "${TOTAL}" "${TEST_COLUMN}" >> report.md
-#              else
-#                printf "| %-11s | %-8s | %-10s %4d / %4d | %s |\n" \
-#                  "" "${MODE}" "${COMPILE_BAR}" "${PASSED}" "${TOTAL}" "${TEST_COLUMN}" >> report.md
-#              fi
-#            done
-#          done
-#
-#      - name: Prepare compilation and run time table
-#        run: |
-#          echo "| Project     | Mode     | Compile (solx/solc/Δs/Δ%)  | Run (solx/solc/Δs/Δ%)  | Size warnings (solx/solc) |" > time_report.md
-#          echo "|-------------|----------|----------------------------|------------------------|---------------------------|" >> time_report.md
-#
-#          PROJECTS=$(yq '. as $root | keys[]' .github/hardhat-projects.toml | tr '\n' ' ')
-#          for PROJECT in ${PROJECTS}; do
-#            for MODE in "default" "viaIR"; do
-#              [ "${MODE}" = "viaIR" ] && SUFFIX="-via-ir" || SUFFIX=""
-#              JSON="data/solx${SUFFIX}/build_${PROJECT}.json"
-#              REF_JSON="data/solc${SUFFIX}/build_${PROJECT}.json"
-#
-#              if [ ! -s "$JSON" ] || [ ! -s "$REF_JSON" ]; then
-#                echo "No data for ${PROJECT} [$MODE]"
-#                continue
-#              fi
-#
-#              if ! (jq empty "${JSON}" > /dev/null 2>&1 && [ -s "${JSON}" ]); then
-#                echo "Invalid JSON for ${PROJECT} [${MODE}]: ${JSON}"
-#                continue
-#              fi
-#
-#              # Bytecode size exceeds limit
-#              BYTECODE_WARN_SOLX=$(jq '[.errors[] | select(.errorCode == "5574" or .errorCode == "3860")] | length' "${JSON}")
-#              BYTECODE_WARN_SOLC=$(jq '[.errors[] | select(.errorCode == "5574" or .errorCode == "3860")] | length' "${REF_JSON}")
-#              BYTECODE_COLUMN=$(printf "%d / %d" "${BYTECODE_WARN_SOLX}" "${BYTECODE_WARN_SOLC}")
-#
-#              COMPILE_SOLX=$(jq -r '.compile_time // 0' "${JSON}")
-#              COMPILE_SOLC=$(jq -r '.compile_time // 0' "${REF_JSON}")
-#              RUN_SOLX=$(jq -r '.exec_time // 0' "${JSON}")
-#              RUN_SOLC=$(jq -r '.exec_time // 0' "${REF_JSON}")
-#
-#              # Compute differences
-#              COMPILE_DIFF=$(awk "BEGIN { printf \"%.2f\", ${COMPILE_SOLX} - ${COMPILE_SOLC} }")
-#              COMPILE_PCT=$(awk "BEGIN {
-#                if (${COMPILE_SOLC} == 0) print \"∞\";
-#                else printf \"%+.0f%%\", ((${COMPILE_SOLX} - ${COMPILE_SOLC}) / ${COMPILE_SOLC}) * 100
-#              }")
-#
-#              RUN_DIFF=$(awk "BEGIN { printf \"%.2f\", ${RUN_SOLX} - ${RUN_SOLC} }")
-#              RUN_PCT=$(awk "BEGIN {
-#                if (${RUN_SOLC} == 0) print \"∞\";
-#                else printf \"%+.0f%%\", ((${RUN_SOLX} - ${RUN_SOLC}) / ${RUN_SOLC}) * 100
-#              }")
-#
-#              # Compile emoji
-#              COMPILE_EMOJI=$(awk "BEGIN {
-#                diff = ${COMPILE_SOLX} - ${COMPILE_SOLC};
-#                pct = ((${COMPILE_SOLC} > 0) ? (diff / ${COMPILE_SOLC}) * 100 : 0);
-#                if (pct > 5) print \"📈\";
-#                else if (pct < -5) print \"📉\";
-#                else print \"➖\";
-#              }")
-#
-#              # Run emoji
-#              RUN_EMOJI=$(awk "BEGIN {
-#                diff = ${RUN_SOLX} - ${RUN_SOLC};
-#                pct = ((${RUN_SOLC} > 0) ? (diff / ${RUN_SOLC}) * 100 : 0);
-#                if (pct > 5) print \"📈\";
-#                else if (pct < -5) print \"📉\";
-#                else print \"➖\";
-#              }")
-#
-#              COMPILE_COLUMN=$(printf "%.2fs / %.2fs / %+0.2fs / %s %s" "$COMPILE_SOLX" "$COMPILE_SOLC" "$COMPILE_DIFF" "$COMPILE_PCT" "$COMPILE_EMOJI")
-#              RUN_COLUMN=$(printf "%.2fs / %.2fs / %+0.2fs / %s %s" "$RUN_SOLX" "$RUN_SOLC" "$RUN_DIFF" "$RUN_PCT" "$RUN_EMOJI")
-#
-#              if [ "$MODE" = "default" ]; then
-#                printf "| %-11s | %-8s | %-28s | %-24s | %-27s |\n" \
-#                  "${PROJECT}" "${MODE}" "${COMPILE_COLUMN}" "${RUN_COLUMN}" "${BYTECODE_COLUMN}" >> time_report.md
-#              else
-#                printf "| %-11s | %-8s | %-28s | %-24s | %-27s |\n" \
-#                  "" "${MODE}" "${COMPILE_COLUMN}" "${RUN_COLUMN}" "${BYTECODE_COLUMN}" >> time_report.md
-#              fi
-#            done
-#          done
-#
-#      - name: Update job summary
-#        run: cat report.md >> "${GITHUB_STEP_SUMMARY}"
-#
-#      - name: Update job summary with time report
-#        run: cat time_report.md >> "${GITHUB_STEP_SUMMARY}"
-#
-#      - name: Upload report
-#        if: ${{ github.event_name == 'pull_request' }}
-#        uses: mshick/add-pr-comment@v2
-#        with:
-#          message-path: report.md
-#          message-id: 'compatibility-matrix'
-#
-#      - name: Upload time report
-#        if: ${{ github.event_name == 'pull_request' }}
-#        uses: mshick/add-pr-comment@v2
-#        with:
-#          message-path: time_report.md
-#          message-id: 'time-report-table'
+  prepare-compatibility-table:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download reports
+        uses: actions/download-artifact@v4
+        with:
+          path: data
+          merge-multiple: 'true'
+
+      - name: Prepare compatibility table
+        run: |
+          echo "| Project     | Mode     | Compilation, solc / solx | Solc, Passed / Total | Solx, Passed / Total |" > report.md
+          echo "|-------------|----------|--------------------------|----------------------|----------------------|" >> report.md
+
+          PROJECTS=$(yq '. as $root | keys[]' .github/hardhat-projects.toml | tr '\n' ' ')
+
+          for PROJECT in ${PROJECTS}; do
+            for MODE in "default" "viaIR"; do
+              if [ "${MODE}" = "default" ]; then
+                SOLX_BUILD_JSON="data/solx/build_${PROJECT}.json"
+                SOLC_BUILD_JSON="data/solc/build_${PROJECT}.json"
+                SOLX_TEST_JSON="data/solx/test_${PROJECT}.json"
+                SOLC_TEST_JSON="data/solc/test_${PROJECT}.json"
+              else
+                SOLX_BUILD_JSON="data/solx-via-ir/build_${PROJECT}.json"
+                SOLC_BUILD_JSON="data/solc-via-ir/build_${PROJECT}.json"
+                SOLX_TEST_JSON="data/solx-via-ir/test_${PROJECT}.json"
+                SOLC_TEST_JSON="data/solc-via-ir/test_${PROJECT}.json"
+              fi
+
+              # Compilation results
+              SOLC_COMPILE_STATUS="N/A"
+              SOLX_COMPILE_STATUS="N/A"
+              if [ -f "$SOLC_BUILD_JSON" ]; then
+                STATUS=$(jq -r '.compile_status' "$SOLC_BUILD_JSON")
+                SOLC_COMPILE_STATUS=$([ "$STATUS" -eq 0 ] && echo "✅" || echo "❌")
+              fi
+              if [ -f "$SOLX_BUILD_JSON" ]; then
+                STATUS=$(jq -r '.compile_status' "$SOLX_BUILD_JSON")
+                SOLX_COMPILE_STATUS=$([ "$STATUS" -eq 0 ] && echo "✅" || echo "❌")
+              fi
+              COMPILE_COLUMN="${SOLC_COMPILE_STATUS} / ${SOLX_COMPILE_STATUS}"
+
+              # Test results
+              read_solc_test() {
+                if [ -s "$SOLC_TEST_JSON" ]; then
+                  TESTS=$(jq -r '.stats.tests' "$SOLC_TEST_JSON")
+                  PASSES=$(jq -r '.stats.passes' "$SOLC_TEST_JSON")
+                  echo "${PASSES} / ${TESTS}"
+                else
+                  COMPILE_STATUS=$(jq -r '.compile_status' "$SOLC_BUILD_JSON")
+                  if [ "$COMPILE_STATUS" -eq 0 ]; then
+                    echo "❌ Run failed"
+                  else
+                    echo "N/A"
+                  fi
+                fi
+              }
+
+              read_solx_test() {
+                if [ -s "$SOLX_TEST_JSON" ]; then
+                  TESTS=$(jq -r '.stats.tests' "$SOLX_TEST_JSON")
+                  PASSES=$(jq -r '.stats.passes' "$SOLX_TEST_JSON")
+                  echo "${PASSES} / ${TESTS}"
+                else
+                  COMPILE_STATUS=$(jq -r '.compile_status' "$SOLX_BUILD_JSON")
+                  if [ "$COMPILE_STATUS" -eq 0 ]; then
+                    echo "❌ Run failed"
+                  else
+                    echo "N/A"
+                  fi
+                fi
+              }
+
+              SOLC_TEST_COLUMN=$(read_solc_test)
+              SOLX_TEST_COLUMN=$(read_solx_test)
+
+              if [ "$MODE" = "default" ]; then
+                printf "| %-11s | %-8s | %-24s | %-20s | %-20s |\n" \
+                  "${PROJECT}" "${MODE}" "${COMPILE_COLUMN}" "${SOLC_TEST_COLUMN}" "${SOLX_TEST_COLUMN}" >> report.md
+              else
+                printf "| %-11s | %-8s | %-24s | %-20s | %-20s |\n" \
+                  "" "${MODE}" "${COMPILE_COLUMN}" "${SOLC_TEST_COLUMN}" "${SOLX_TEST_COLUMN}" >> report.md
+              fi
+            done
+          done
+
+      - name: Update job summary
+        run: cat report.md >> "${GITHUB_STEP_SUMMARY}"
+
+      - name: Upload report
+        if: ${{ github.event_name == 'pull_request' }}
+        uses: mshick/add-pr-comment@v2
+        with:
+          message-path: report.md
+          message-id: 'hardhat-compatibility-matrix'
